In [1]:
import numpy as np

In [2]:
type ([1,2,3])

list

In [4]:
arreglo_np = np.array([1,2,3])


In [5]:
type(arreglo_np)

numpy.ndarray

In [6]:
tupla_np = np.array((1,2,3))

In [7]:
type(tupla_np)

numpy.ndarray

In [8]:
np.zeros((1))

array([0.])

In [9]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((5, 2)) #tupla

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.zeros([5,2,3,4])

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [14]:
np.ones(1)

array([1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [24]:
np.empty((1,2,3,4)) #se llena con numeros random, si se utiliza se debe llenar 

array([[[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
          2.55895886e-307],
         [2.33645657e-307, 2.00268361e-307, 2.22523004e-307,
          1.29062229e-306],
         [1.69121367e-306, 1.78020169e-306, 6.23053954e-307,
          7.56555670e-307]],

        [[1.60218491e-306, 1.33507487e-306, 1.33511018e-306,
          1.29057340e-306],
         [9.34610469e-307, 1.69119330e-306, 7.56591659e-307,
          1.00132398e-307],
         [1.29062229e-306, 6.89804133e-307, 1.11261162e-306,
          8.34443015e-308]]]])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
np.arange(3,10) # el primer parametro es desde donde empezamos el segundo parametro es hasta donde

array([3, 4, 5, 6, 7, 8, 9])

In [31]:
arreglo_pares = np.arange(0,20,2) #el tercer parametro son los saltos

In [33]:
arreglo_pares.size

10

In [34]:
arreglo_pares.shape

(10,)

In [35]:
arreglo_pares.reshape([5, 2])

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [37]:
np.arange(24).reshape((6,2,2)) #como se podria utilizar

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [41]:
np.arange(100000).reshape(10000, 10)

array([[    0,     1,     2, ...,     7,     8,     9],
       [   10,    11,    12, ...,    17,    18,    19],
       [   20,    21,    22, ...,    27,    28,    29],
       ...,
       [99970, 99971, 99972, ..., 99977, 99978, 99979],
       [99980, 99981, 99982, ..., 99987, 99988, 99989],
       [99990, 99991, 99992, ..., 99997, 99998, 99999]])

In [42]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [45]:
# suma
print(a + b)

[15 15 15]


In [46]:
# resta
a - b

array([5, 5, 5])

In [47]:
# multiplicacion
a * b

array([50, 50, 50])

In [48]:
# divisiones
a / b

array([2., 2., 2.])

In [50]:
# modulo
a % b

array([0, 0, 0], dtype=int32)

In [51]:
a / 2

array([5., 5., 5.])

In [52]:
a % 2

array([0, 0, 0], dtype=int32)

In [53]:
a + 10

array([20, 20, 20])

In [54]:
a - 3

array([7, 7, 7])

In [55]:
a * 52

array([520, 520, 520])

In [58]:
arreglo_doce = np.arange(12)
arreglo_doce 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
arreglo_doce > 5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [59]:
A = np.arange(4).reshape((2,2)) 
A 

array([[0, 1],
       [2, 3]])

In [61]:
B = np.arange(4,8).reshape((2,2))
B 

array([[4, 5],
       [6, 7]])

In [62]:
A * B

array([[ 0,  5],
       [12, 21]])

In [63]:
A + B

array([[ 4,  6],
       [ 8, 10]])

In [64]:
A - B

array([[-4, -4],
       [-4, -4]])

In [65]:
A / B

array([[0.        , 0.2       ],
       [0.33333333, 0.42857143]])

In [66]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [67]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [69]:
Resultado = np.arange(4).reshape(2,2)
np.dot(A,B,Resultado)

array([[ 6,  7],
       [26, 31]])

In [70]:
Resultado

array([[ 6,  7],
       [26, 31]])

In [72]:
arreglo_tres = np.arange(3)
arreglo_tres += 2

In [73]:
arreglo_tres

array([2, 3, 4])

In [74]:
arreglo_tres.sum()

9

In [76]:
arreglo_tres.min()

2

In [77]:
arreglo_tres.max()

4

In [83]:
arreglo_tres_cuatro = np.arange(24).reshape(6,2,2)
arreglo_tres_cuatro

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [84]:
arreglo_tres_cuatro.sum()


276

In [85]:
arreglo_tres_cuatro.sum(axis=0)

array([[60, 66],
       [72, 78]])

In [86]:
arreglo_tres_cuatro.sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20],
       [26, 28],
       [34, 36],
       [42, 44]])

In [87]:
arreglo_tres_cuatro.sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21],
       [25, 29],
       [33, 37],
       [41, 45]])