# Universal Functions

In [1]:
import numpy as np

In [3]:
angulos_cero_noventa = np.array((0,30,45,60,90))
angulos_cero_noventa

array([ 0, 30, 45, 60, 90])

In [4]:
np.pi

3.141592653589793

In [6]:
angulos_radianes = angulos_cero_noventa * np.pi / 180
angulos_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [7]:
np.sin(angulos_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [8]:
np.cos(angulos_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [9]:
np.tan(angulos_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [14]:
arreglo_random_diez = np.random.randint(-10, #Menor
                                        1000, #Mayor
                                        10) #Tamanio
arreglo_random_diez = arreglo_random_diez * 10
arreglo_random_diez

array([8540, 9120, 6050, 9210, 5960,  590, 3500,  590, 1860, 1920])

In [21]:
np.random.randint(10)

7

In [22]:
# Media
arreglo_random_diez.mean() 

4734.0

In [23]:
# Mediana
np.median(arreglo_random_diez)

4730.0

In [24]:
# Desviacion estandar
np.std(arreglo_random_diez)

3302.102966292844

In [25]:
# Varianza
np.var(arreglo_random_diez)

10903884.0